class CompletionsData:
    _WHAT_COMPLETIONS = [
        "Housing",
        "AgeGroup",
        "Gender",
        "Households",
        "DrinkingWater",
        "CookingFuel",
        "Lighting",
        "Toilet",
        "Ethnicity",
        "Religion",
        "Population",
        "Population:Ethnicity",
        "Population:AgeGroup",
        "Population:Gender",
        "Population:Religion",
        "Election",
        "Election:Presidential",
        "Election:General",
        "Economy",
        "Education",
        "Social",
        "*",
    ]

    _WHERE_COMPLETIONS = [
        "LK",
        "LK:Provinces",
        "LK:Districts",
        "LK:DSDs",
        "LK:GNDs",
        "LK-1",
        "LK-2",
        "LK-3",
        "LK-4",
        "LK-5",
        "LK-6",
        "LK-7",
        "LK-8",
        "LK-9",
        "*",
    ]
