class Style:
    FONT_SIZE_TITLE = 18
    FONT_SIZE_PANEL = 15
    FONT_SIZE_METADATA = 11

    COLOR_TITLE = "#111111"
    COLOR_PANEL = "#333333"
    COLOR_METADATA = "#888888"

    COLOR_SURFACE_HEADER = "#eeeeee"
    COLOR_SURFACE_FOOTER = "#ffffff"

    COLOR_AXIS = "#666666"
    COLOR_GRID = "#dddddd"
