class Census2024ColRenamesMixin:
    _COL_RENAMES: dict[str, dict[str, str]] = {
        "Housing": {
            "occupied_housing_units": "OccupiedHousingUnits",
        },
        "AgeGroup": {
            "total": "Total",
            "age_0_14": "Age0To14",
            "age_15_59": "Age15To59",
            "age_60_64": "Age60To64",
            "age_65_and_above": "Age65AndAbove",
        },
        "Gender": {
            "total": "Total",
            "male": "Male",
            "female": "Female",
        },
        "Households": {
            "n_households": "Households",
        },
        "DrinkingWater": {
            "protected_well": "ProtectedWell",
            "semi_protected_well": "SemiProtectedWell",
            "unprotected_well": "UnprotectedWell",
            "tube_well": "TubeWell",
            "spring_fountain": "SpringFountain",
            "pipe_borne_nwsdb": "PipeBorneNWSDB",
            "pipe_borne_local_authority": "PipeBorneLocalAuthority",
            "pipe_borne_community": "PipeBorneCommunity",
            "pipe_borne_private": "PipeBornePrivate",
            "tank_river_stream": "TankRiverStream",
            "rain_water": "RainWater",
            "bottled_water": "BottledWater",
            "filter_ro": "FilterRO",
            "bowser": "Bowser",
            "other": "Other",
        },
        "CookingFuel": {
            "firewood": "Firewood",
            "kerosene": "Kerosene",
            "gas": "Gas",
            "electricity": "Electricity",
            "sawdust_paddy_husk": "SawdustOrPaddyHusk",
            "bio_gas": "BioGas",
            "other": "Other",
            "not_relevant": "NotRelevant",
        },
        "Lighting": {
            "electricity_grid": "ElectricityGrid",
            "kerosene_lamp": "KeroseneLamp",
            "solar_grid": "SolarGrid",
            "solar_standalone": "SolarStandalone",
            "bio_gas": "BioGas",
            "generator": "Generator",
            "other": "Other",
        },
        "Toilet": {
            "within_unit_exclusive": "WithinUnitExclusive",
            "within_unit_shared": "WithinUnitShared",
            "within_premises_exclusive": "WithinPremisesExclusive",
            "within_premises_shared": "WithinPremisesShared",
            "no_toilet_sharing": "NoToiletSharing",
            "common_public": "CommonPublic",
            "none": "NoToilet",
        },
        "Ethnicity": {
            "total": "Total",
            "sinhalese": "Sinhalese",
            "sri_lanka_tamil": "SriLankaTamil",
            "indian_tamil_or_malaiyaga_thamilar": "IndianTamil",
            "sri_lanka_moor_or_muslim": "SriLankaMoor",
            "burgher": "Burgher",
            "malay": "Malay",
            "sri_lanka_chetty": "SriLankaChetty",
            "bharatha": "Bharatha",
            "veddhas": "Veddha",
            "other": "Other",
        },
        "Religion": {
            "total": "Total",
            "buddhist": "Buddhist",
            "hindu": "Hindu",
            "islam": "Islam",
            "roman_catholic": "RomanCatholic",
            "other_christian": "OtherChristian",
            "other": "Other",
        },
    }
