// Auto-generated by javascript_version.py

export const DATETIME_STR = "2026-08-01 07:15";
export const VERSION_DATETIME = new Date(DATETIME_STR);

const VERSION = { DATETIME_STR, VERSION_DATETIME };
export default VERSION;
