#!/usr/bin/env python3
"""Build ThingFactory.js by scanning for classes that extend Thing."""

import os
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE_DIR = ROOT / "src" / "nonview" / "core"
THING_FACTORY_PATH = CORE_DIR / "thing" / "ThingFactory.js"

CLASS_RE = re.compile(
    r"export\s+default\s+class\s+(\w+)\s*(?:extends\s+(\w+)\s*)?\{"
)


def find_class_files():
    """Yield (path, class_name, parent_name) for every class in src/nonview/core."""
    for path in CORE_DIR.rglob("*.js"):
        text = path.read_text(encoding="utf-8")
        match = CLASS_RE.search(text)
        if match:
            class_name = match.group(1)
            parent_name = match.group(2)
            yield path, class_name, parent_name


def relative_import_path(class_path, factory_path):
    """Return the relative JS import path from factory_path to class_path."""
    rel = os.path.relpath(class_path.parent, factory_path.parent)
    if rel == ".":
        prefix = "./"
    else:
        prefix = "./" + rel.replace(os.sep, "/") + "/"
    return f"{prefix}{class_path.stem}.js"


def extends_thing(class_name, class_to_parent):
    """Return True if class_name extends Thing (directly or transitively)."""
    seen = set()
    current = class_name
    while current and current not in seen:
        seen.add(current)
        if current == "Thing":
            return True
        current = class_to_parent.get(current)
    return False


def main():
    classes = list(find_class_files())
    class_to_parent = {name: parent for _, name, parent in classes if parent}

    thing_classes = [
        (path, name)
        for path, name, parent in classes
        if name != "Thing" and extends_thing(name, class_to_parent)
    ]
    thing_classes.sort(key=lambda item: item[1])

    # Group by immediate parent directory name (e.g. concept, entity, category_concept)
    by_folder = {}
    for class_path, class_name in thing_classes:
        folder = class_path.parent.name
        by_folder.setdefault(folder, []).append((class_path, class_name))

    imports = []
    statics = []
    for folder, items in sorted(by_folder.items()):
        statics.append(f"  // {folder}")
        for class_path, class_name in items:
            import_path = relative_import_path(class_path, THING_FACTORY_PATH)
            imports.append(f'import {class_name} from "{import_path}";')
            statics.append(f"  static {class_name} = {class_name};")
        statics.append("")

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header_lines = [
        "// ⚠️ DO NOT EDIT.",
        "// Auto-generated by src_py/build_thing_factory.py at ",
        f"// {generated_at}",
        "",
        "",
    ]

    content = "\n".join(header_lines)
    content += "\n".join(imports) + "\n\n"
    content += "export default class ThingFactory {\n"
    content += "\n".join(statics)
    if statics:
        content += "\n"
    content += "}\n"

    THING_FACTORY_PATH.write_text(content, encoding="utf-8")
    print(f"Updated {THING_FACTORY_PATH}")
    for _, class_name in thing_classes:
        print(f"  - {class_name}")


if __name__ == "__main__":
    main()
