#!/usr/bin/env python3
"""Build split ThingFactory contents by scanning classes that extend Thing."""
import os
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
CORE_DIR = ROOT / "src" / "nonview" / "core"
FACTORY_DIR = CORE_DIR / "thing" / "thing_factory"
INDEX_PATH = FACTORY_DIR / "ThingFactoryContentsMixin.js"
PART_SIZE = 25
CLASS_RE = re.compile(
    r"export\s+default\s+class\s+(\w+)\s*(?:extends\s+(\w+)\s*)?\{"
)
def find_classes():
    """Return path, class name, and parent for each core class."""
    classes = []
    for path in CORE_DIR.rglob("*.js"):
        match = CLASS_RE.search(path.read_text(encoding="utf-8"))
        if match:
            classes.append((path, match.group(1), match.group(2)))
    return classes
def extends_thing(class_name, parents):
    """Return whether a class transitively extends Thing."""
    seen = set()
    while class_name and class_name not in seen:
        seen.add(class_name)
        if class_name == "Thing":
            return True
        class_name = parents.get(class_name)
    return False
def import_path(class_path):
    """Return the JS import path from the factory directory."""
    relative = os.path.relpath(class_path, FACTORY_DIR).replace(os.sep, "/")
    return relative if relative.startswith(".") else f"./{relative}"
def write_part(part_number, classes):
    """Write one bounded-size factory content module."""
    path = FACTORY_DIR / f"ThingFactoryContentsPart{part_number}.js"
    imports = [
        f'import {name} from "{import_path(class_path)}";'
        for class_path, name in classes
    ]
    properties = [f"  {name}," for _, name in classes]
    content = "\n".join(
        [
            "// Auto-generated by src_py/build_thing_factory.py.",
            *imports,
            "",
            "const thingFactoryContents = {",
            *properties,
            "};",
            "",
            "export default thingFactoryContents;",
            "",
        ]
    )
    path.write_text(content, encoding="utf-8")
    return path
def write_index(part_paths):
    """Write the module that combines generated content parts."""
    imports = [
        f'import part{index} from "./{path.name}";'
        for index, path in enumerate(part_paths, 1)
    ]
    spreads = [f"  ...part{index}," for index in range(1, len(part_paths) + 1)]
    content = "\n".join(
        [
            "// Auto-generated by src_py/build_thing_factory.py.",
            *imports,
            "",
            "const thingFactoryContents = {",
            *spreads,
            "};",
            "",
            "export default thingFactoryContents;",
            "",
        ]
    )
    INDEX_PATH.write_text(content, encoding="utf-8")
def main():
    classes = find_classes()
    parents = {name: parent for _, name, parent in classes if parent}
    things = sorted(
        (
            (path, name)
            for path, name, _ in classes
            if name != "Thing" and extends_thing(name, parents)
        ),
        key=lambda item: item[1],
    )
    for old_part in FACTORY_DIR.glob("ThingFactoryContentsPart*.js"):
        old_part.unlink()
    parts = [
        write_part(index, things[start : start + PART_SIZE])
        for index, start in enumerate(range(0, len(things), PART_SIZE), 1)
    ]
    write_index(parts)
    print(f"Updated {INDEX_PATH} in {len(parts)} parts")
if __name__ == "__main__":
    main()
