#!/usr/bin/env python3
"""Build the ThingFactory registry by scanning classes that extend Thing."""

import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE_DIR = ROOT / "src" / "nonview" / "core"
FACTORY_DIR = CORE_DIR / "thing" / "thing_factory"
GENERATED_DIR = FACTORY_DIR / "generated"
CONTENTS_PATH = FACTORY_DIR / "ThingFactoryContentsMixin.js"
CLASS_RE = re.compile(
    r"export\s+default\s+class\s+(\w+)\s*(?:extends\s+(\w+)\s*)?\{"
)
HEADER = [
    "// ⚠️ DO NOT EDIT.",
    "// Auto-generated by src_py/build_thing_factory.py.",
    "",
]


def find_classes():
    classes = []
    for path in CORE_DIR.rglob("*.js"):
        match = CLASS_RE.search(path.read_text(encoding="utf-8"))
        if match:
            classes.append((path, *match.groups()))
    return classes


def extends_thing(class_name, class_to_parent):
    seen = set()
    current = class_name
    while current and current not in seen:
        seen.add(current)
        if current == "Thing":
            return True
        current = class_to_parent.get(current)
    return False


def relative_import_path(class_path, output_path):
    relative = os.path.relpath(class_path, output_path.parent)
    return "./" + relative.replace(os.sep, "/")


def group_file_name(folder):
    return "".join(part.title() for part in folder.split("_"))


def write_group(folder, items):
    output_path = GENERATED_DIR / f"{group_file_name(folder)}.js"
    imports = [
        f'import {name} from "{relative_import_path(path, output_path)}";'
        for path, name in items
    ]
    names = ",\n  ".join(name for _, name in items)
    registry_name = f"{output_path.stem}Registry"
    content = "\n".join(HEADER + imports)
    content += f"\n\nconst {registry_name} = {{\n  {names},\n}};\n"
    content += f"\nexport default {registry_name};\n"
    output_path.write_text(content, encoding="utf-8")
    return output_path


def main():
    classes = find_classes()
    parents = {name: parent for _, name, parent in classes if parent}
    thing_classes = [
        (path, name)
        for path, name, _ in classes
        if name != "Thing" and extends_thing(name, parents)
    ]
    groups = {}
    for path, name in sorted(thing_classes, key=lambda item: item[1]):
        groups.setdefault(path.parent.name, []).append((path, name))

    GENERATED_DIR.mkdir(exist_ok=True)
    for path in GENERATED_DIR.glob("*.js"):
        path.unlink()
    group_paths = [
        write_group(folder, items) for folder, items in sorted(groups.items())
    ]
    imports = [
        f'import {path.stem} from "./generated/{path.name}";'
        for path in group_paths
    ]
    names = ", ".join(path.stem for path in group_paths)
    content = "\n".join(HEADER + imports)
    content += f"\n\nconst ThingFactoryContents = Object.assign({{}}, {names});\n"
    content += "\nexport default ThingFactoryContents;\n"
    CONTENTS_PATH.write_text(content, encoding="utf-8")
    print(f"Updated {CONTENTS_PATH} and {len(group_paths)} grouped modules")


if __name__ == "__main__":
    main()
