// ⚠️ DO NOT EDIT.
// Auto-generated by src_py/build_thing_factory.py at
// 2026-08-02 05:29:19

import Bool from "./../concept/atoms/Bool.js";
import Float from "./../concept/atoms/Float.js";
import Int from "./../concept/atoms/Int.js";
import Percent from "./../concept/atoms/Percent.js";
import Time from "./../concept/atoms/Time.js";
import CategoryConcept from "./../concept/category_concept/CategoryConcept.js";
import Ethnicity from "./../concept/category_concept/Ethnicity.js";
import Religion from "./../concept/category_concept/Religion.js";
import CensusOfficer from "./../concept/category_concept/census/CensusOfficer.js";
import CensusTopic from "./../concept/category_concept/census/CensusTopic.js";
import Concept from "./../concept/Concept.js";
import ElectionType from "./../concept/category_concept/election/ElectionType.js";
import Party from "./../concept/category_concept/election/Party.js";
import Summary from "./../concept/category_concept/election/Summary.js";
import Census from "./../entity/Census.js";
import Entity from "./../entity/Entity.js";
import House from "./../entity/House.js";
import Person from "./../entity/Person.js";
import Vote from "./../entity/Vote.js";
import AdministrativeEntity from "./../concept/category_concept/government/AdministrativeEntity.js";
import Sector from "./../concept/category_concept/government/Sector.js";
import CookingFuel from "./../concept/category_concept/household/CookingFuel.js";
import FloorType from "./../concept/category_concept/household/FloorType.js";
import HouseholdAppliances from "./../concept/category_concept/household/HouseholdAppliances.js";
import HouseholdOccupancy from "./../concept/category_concept/household/HouseholdOccupancy.js";
import HouseholdSize from "./../concept/category_concept/household/HouseholdSize.js";
import HouseholdStructure from "./../concept/category_concept/household/HouseholdStructure.js";
import HouseholdType from "./../concept/category_concept/household/HouseholdType.js";
import Lighting from "./../concept/category_concept/household/Lighting.js";
import LiquidWasteDisposal from "./../concept/category_concept/household/LiquidWasteDisposal.js";
import LivingQuarters from "./../concept/category_concept/household/LivingQuarters.js";
import OccupationStatus from "./../concept/category_concept/household/OccupationStatus.js";
import OneRoomOrMore from "./../concept/category_concept/household/OneRoomOrMore.js";
import OwnershipStatus from "./../concept/category_concept/household/OwnershipStatus.js";
import RoofType from "./../concept/category_concept/household/RoofType.js";
import SolidWasteDisposal from "./../concept/category_concept/household/SolidWasteDisposal.js";
import SourceOfDrinkingWater from "./../concept/category_concept/household/SourceOfDrinkingWater.js";
import ToiletFacilities from "./../concept/category_concept/household/ToiletFacilities.js";
import TypeOfUnit from "./../concept/category_concept/household/TypeOfUnit.js";
import WallType from "./../concept/category_concept/household/WallType.js";
import WaterSupplyAvailability from "./../concept/category_concept/household/WaterSupplyAvailability.js";
import AgeGroup from "./../concept/category_concept/person/AgeGroup.js";
import AgeGroupWorking from "./../concept/category_concept/person/AgeGroupWorking.js";
import DisabilityTypes from "./../concept/category_concept/person/DisabilityTypes.js";
import EconomicInactivityReason from "./../concept/category_concept/person/EconomicInactivityReason.js";
import EducationActivity from "./../concept/category_concept/person/EducationActivity.js";
import EmmigrationReason from "./../concept/category_concept/person/EmmigrationReason.js";
import EmploymentStatus from "./../concept/category_concept/person/EmploymentStatus.js";
import HighestEducationLevel from "./../concept/category_concept/person/HighestEducationLevel.js";
import HighestEducationLevel2 from "./../concept/category_concept/person/HighestEducationLevel2.js";
import HighestEducationLevel3 from "./../concept/category_concept/person/HighestEducationLevel3.js";
import IsEconomicallyActive from "./../concept/category_concept/person/IsEconomicallyActive.js";
import LanguageLiteracy from "./../concept/category_concept/person/LanguageLiteracy.js";
import LiveBirths from "./../concept/category_concept/person/LiveBirths.js";
import MaritalStatus from "./../concept/category_concept/person/MaritalStatus.js";
import MigrationDirection from "./../concept/category_concept/person/MigrationDirection.js";
import MigrationLifetimeDirection from "./../concept/category_concept/person/MigrationLifetimeDirection.js";
import MigrationReason from "./../concept/category_concept/person/MigrationReason.js";
import MigrationStatus from "./../concept/category_concept/person/MigrationStatus.js";
import NonCommunicableDisease from "./../concept/category_concept/person/NonCommunicableDisease.js";
import ResidentRelativeToDistrict from "./../concept/category_concept/person/ResidentRelativeToDistrict.js";
import Sex from "./../concept/category_concept/person/Sex.js";
import SingleOrMultipleDisabilities from "./../concept/category_concept/person/SingleOrMultipleDisabilities.js";
import Country from "./../concept/category_concept/region/Country.js";
import DSD from "./../concept/category_concept/region/DSD.js";
import District from "./../concept/category_concept/region/District.js";
import ED from "./../concept/category_concept/region/ED.js";
import GND from "./../concept/category_concept/region/GND.js";
import PD from "./../concept/category_concept/region/PD.js";
import Province from "./../concept/category_concept/region/Province.js";
import Region from "../concept/category_concept/region/region/Region.js";
import TimeDurationGroup from "./../concept/time/TimeDurationGroup.js";
import TimeGroup0510More from "./../concept/time/TimeGroup0510More.js";

export default class ThingFactory {
  // atoms
  static Bool = Bool;
  static Float = Float;
  static Int = Int;
  static Percent = Percent;
  static Time = Time;

  // category_concept
  static CategoryConcept = CategoryConcept;
  static Ethnicity = Ethnicity;
  static Religion = Religion;

  // census
  static CensusOfficer = CensusOfficer;
  static CensusTopic = CensusTopic;

  // concept
  static Concept = Concept;

  // election
  static ElectionType = ElectionType;
  static Party = Party;
  static Summary = Summary;

  // entity
  static Census = Census;
  static Entity = Entity;
  static House = House;
  static Person = Person;
  static Vote = Vote;

  // government
  static AdministrativeEntity = AdministrativeEntity;
  static Sector = Sector;

  // household
  static CookingFuel = CookingFuel;
  static FloorType = FloorType;
  static HouseholdAppliances = HouseholdAppliances;
  static HouseholdOccupancy = HouseholdOccupancy;
  static HouseholdSize = HouseholdSize;
  static HouseholdStructure = HouseholdStructure;
  static HouseholdType = HouseholdType;
  static Lighting = Lighting;
  static LiquidWasteDisposal = LiquidWasteDisposal;
  static LivingQuarters = LivingQuarters;
  static OccupationStatus = OccupationStatus;
  static OneRoomOrMore = OneRoomOrMore;
  static OwnershipStatus = OwnershipStatus;
  static RoofType = RoofType;
  static SolidWasteDisposal = SolidWasteDisposal;
  static SourceOfDrinkingWater = SourceOfDrinkingWater;
  static ToiletFacilities = ToiletFacilities;
  static TypeOfUnit = TypeOfUnit;
  static WallType = WallType;
  static WaterSupplyAvailability = WaterSupplyAvailability;

  // person
  static AgeGroup = AgeGroup;
  static AgeGroupWorking = AgeGroupWorking;
  static DisabilityTypes = DisabilityTypes;
  static EconomicInactivityReason = EconomicInactivityReason;
  static EducationActivity = EducationActivity;
  static EmmigrationReason = EmmigrationReason;
  static EmploymentStatus = EmploymentStatus;
  static HighestEducationLevel = HighestEducationLevel;
  static HighestEducationLevel2 = HighestEducationLevel2;
  static HighestEducationLevel3 = HighestEducationLevel3;
  static IsEconomicallyActive = IsEconomicallyActive;
  static LanguageLiteracy = LanguageLiteracy;
  static LiveBirths = LiveBirths;
  static MaritalStatus = MaritalStatus;
  static MigrationDirection = MigrationDirection;
  static MigrationLifetimeDirection = MigrationLifetimeDirection;
  static MigrationReason = MigrationReason;
  static MigrationStatus = MigrationStatus;
  static NonCommunicableDisease = NonCommunicableDisease;
  static ResidentRelativeToDistrict = ResidentRelativeToDistrict;
  static Sex = Sex;
  static SingleOrMultipleDisabilities = SingleOrMultipleDisabilities;

  // region
  static Country = Country;
  static DSD = DSD;
  static District = District;
  static ED = ED;
  static GND = GND;
  static PD = PD;
  static Province = Province;
  static Region = Region;

  // time
  static TimeDurationGroup = TimeDurationGroup;
  static TimeGroup0510More = TimeGroup0510More;
}
