// Auto-generated by src_py/build_thing_factory.py.
import AdministrativeEntity from "../concept/category_concept/government/AdministrativeEntity.js";
import AgeGroup from "../concept/category_concept/person/AgeGroup.js";
import AgeGroupWorking from "../concept/category_concept/person/AgeGroupWorking.js";
import Bool from "../concept/atoms/Bool.js";
import CategoryConcept from "../concept/category_concept/CategoryConcept.js";
import Census from "../entity/Census.js";
import CensusOfficer from "../concept/category_concept/census/CensusOfficer.js";
import CensusTopic from "../concept/category_concept/census/CensusTopic.js";
import Concept from "../concept/Concept.js";
import CookingFuel from "../concept/category_concept/household/CookingFuel.js";
import Country from "../concept/category_concept/region/Country.js";
import DSD from "../concept/category_concept/region/DSD.js";
import DisabilityTypes from "../concept/category_concept/person/DisabilityTypes.js";
import District from "../concept/category_concept/region/District.js";
import ED from "../concept/category_concept/region/ED.js";
import EconomicInactivityReason from "../concept/category_concept/person/EconomicInactivityReason.js";
import EducationActivity from "../concept/category_concept/person/EducationActivity.js";
import ElectionType from "../concept/category_concept/election/ElectionType.js";
import EmmigrationReason from "../concept/category_concept/person/EmmigrationReason.js";
import EmploymentStatus from "../concept/category_concept/person/EmploymentStatus.js";
import Entity from "../entity/Entity.js";
import Ethnicity from "../concept/category_concept/Ethnicity.js";
import Float from "../concept/atoms/Float.js";
import FloorType from "../concept/category_concept/household/FloorType.js";
import GND from "../concept/category_concept/region/GND.js";

const thingFactoryContents = {
  AdministrativeEntity,
  AgeGroup,
  AgeGroupWorking,
  Bool,
  CategoryConcept,
  Census,
  CensusOfficer,
  CensusTopic,
  Concept,
  CookingFuel,
  Country,
  DSD,
  DisabilityTypes,
  District,
  ED,
  EconomicInactivityReason,
  EducationActivity,
  ElectionType,
  EmmigrationReason,
  EmploymentStatus,
  Entity,
  Ethnicity,
  Float,
  FloorType,
  GND,
};

export default thingFactoryContents;
