// Auto-generated by src_py/build_thing_factory.py.
import HighestEducationLevel from "../concept/category_concept/person/HighestEducationLevel.js";
import HighestEducationLevel2 from "../concept/category_concept/person/HighestEducationLevel2.js";
import HighestEducationLevel3 from "../concept/category_concept/person/HighestEducationLevel3.js";
import House from "../entity/House.js";
import HouseholdAppliances from "../concept/category_concept/household/HouseholdAppliances.js";
import HouseholdOccupancy from "../concept/category_concept/household/HouseholdOccupancy.js";
import HouseholdSize from "../concept/category_concept/household/HouseholdSize.js";
import HouseholdStructure from "../concept/category_concept/household/HouseholdStructure.js";
import HouseholdType from "../concept/category_concept/household/HouseholdType.js";
import Int from "../concept/atoms/Int.js";
import IsEconomicallyActive from "../concept/category_concept/person/IsEconomicallyActive.js";
import LanguageLiteracy from "../concept/category_concept/person/LanguageLiteracy.js";
import Lighting from "../concept/category_concept/household/Lighting.js";
import LiquidWasteDisposal from "../concept/category_concept/household/LiquidWasteDisposal.js";
import LiveBirths from "../concept/category_concept/person/LiveBirths.js";
import LivingQuarters from "../concept/category_concept/household/LivingQuarters.js";
import MaritalStatus from "../concept/category_concept/person/MaritalStatus.js";
import MigrationDirection from "../concept/category_concept/person/MigrationDirection.js";
import MigrationLifetimeDirection from "../concept/category_concept/person/MigrationLifetimeDirection.js";
import MigrationReason from "../concept/category_concept/person/MigrationReason.js";
import MigrationStatus from "../concept/category_concept/person/MigrationStatus.js";
import NonCommunicableDisease from "../concept/category_concept/person/NonCommunicableDisease.js";
import OccupationStatus from "../concept/category_concept/household/OccupationStatus.js";
import OneRoomOrMore from "../concept/category_concept/household/OneRoomOrMore.js";
import OwnershipStatus from "../concept/category_concept/household/OwnershipStatus.js";

const thingFactoryContents = {
  HighestEducationLevel,
  HighestEducationLevel2,
  HighestEducationLevel3,
  House,
  HouseholdAppliances,
  HouseholdOccupancy,
  HouseholdSize,
  HouseholdStructure,
  HouseholdType,
  Int,
  IsEconomicallyActive,
  LanguageLiteracy,
  Lighting,
  LiquidWasteDisposal,
  LiveBirths,
  LivingQuarters,
  MaritalStatus,
  MigrationDirection,
  MigrationLifetimeDirection,
  MigrationReason,
  MigrationStatus,
  NonCommunicableDisease,
  OccupationStatus,
  OneRoomOrMore,
  OwnershipStatus,
};

export default thingFactoryContents;
