// ⚠️ DO NOT EDIT.
// Auto-generated by src_py/build_thing_factory.py.

import Atoms from "./generated/Atoms.js";
import CategoryConcept from "./generated/CategoryConcept.js";
import Census from "./generated/Census.js";
import Concept from "./generated/Concept.js";
import Election from "./generated/Election.js";
import Entity from "./generated/Entity.js";
import Government from "./generated/Government.js";
import Household from "./generated/Household.js";
import Person from "./generated/Person.js";
import Region from "./generated/Region.js";
import Time from "./generated/Time.js";

const ThingFactoryContents = Object.assign(
  {},
  Atoms,
  CategoryConcept,
  Census,
  Concept,
  Election,
  Entity,
  Government,
  Household,
  Person,
  Region,
  Time,
);

export default ThingFactoryContents;
