// Auto-generated by src_py/build_thing_factory.py.
import part1 from "./ThingFactoryContentsPart1.js";
import part2 from "./ThingFactoryContentsPart2.js";
import part3 from "./ThingFactoryContentsPart3.js";

const thingFactoryContents = {
  ...part1,
  ...part2,
  ...part3,
};

export default thingFactoryContents;
