// Auto-generated by src_py/build_thing_factory.py.
import PD from "../concept/category_concept/region/PD.js";
import Party from "../concept/category_concept/election/Party.js";
import Percent from "../concept/atoms/Percent.js";
import Person from "../entity/Person.js";
import Province from "../concept/category_concept/region/Province.js";
import Region from "../concept/category_concept/region/region/Region.js";
import Religion from "../concept/category_concept/Religion.js";
import ResidentRelativeToDistrict from "../concept/category_concept/person/ResidentRelativeToDistrict.js";
import RoofType from "../concept/category_concept/household/RoofType.js";
import Sector from "../concept/category_concept/government/Sector.js";
import Sex from "../concept/category_concept/person/Sex.js";
import SingleOrMultipleDisabilities from "../concept/category_concept/person/SingleOrMultipleDisabilities.js";
import SolidWasteDisposal from "../concept/category_concept/household/SolidWasteDisposal.js";
import SourceOfDrinkingWater from "../concept/category_concept/household/SourceOfDrinkingWater.js";
import Summary from "../concept/category_concept/election/Summary.js";
import Time from "../concept/atoms/Time.js";
import TimeDurationGroup from "../concept/time/TimeDurationGroup.js";
import TimeGroup0510More from "../concept/time/TimeGroup0510More.js";
import ToiletFacilities from "../concept/category_concept/household/ToiletFacilities.js";
import TypeOfUnit from "../concept/category_concept/household/TypeOfUnit.js";
import Vote from "../entity/Vote.js";
import WallType from "../concept/category_concept/household/WallType.js";
import WaterSupplyAvailability from "../concept/category_concept/household/WaterSupplyAvailability.js";

const thingFactoryContents = {
  PD,
  Party,
  Percent,
  Person,
  Province,
  Region,
  Religion,
  ResidentRelativeToDistrict,
  RoofType,
  Sector,
  Sex,
  SingleOrMultipleDisabilities,
  SolidWasteDisposal,
  SourceOfDrinkingWater,
  Summary,
  Time,
  TimeDurationGroup,
  TimeGroup0510More,
  ToiletFacilities,
  TypeOfUnit,
  Vote,
  WallType,
  WaterSupplyAvailability,
};

export default thingFactoryContents;
